anticreeper:
  enabled: true
  placedonly: true

antienderman:
  enabled: true
  exceptions: false
  list: [grass_block,dirt,sand]

brewingxp:
  enabled: true
  brewxp: [4,6]

farmingrework:
  enabled: true
  farmxp: [1,2]

godapples:
  enabled: true

grieflogs:
  enabled: false

noelytra:
  overworld: true
  nether: true
  end: false

logs:
  enabled: true
  op: false
  level: 0